POST http://localhost:8000/api/token/
Content-Type: application/json

{
    "username": "admin",
    "password": "1234"
}

###
GET http://localhost:8000/api/menus/today/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzOTczNjY2LCJpYXQiOjE3NDM5NzMzNjYsImp0aSI6IjcwMDQxNGU0NzYwOTRhNDhiNWRjNjI1NTUwM2UwY2IxIiwidXNlcl9pZCI6MX0.1uedpYIJbriqns0pvfUiTlu_gC8dS44eWacvHMl3tK8
Accept: application/json; version=v2
Content-Type: application/json

###
GET http://localhost:8000/api/menus/today/results/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzOTc1MDY3LCJpYXQiOjE3NDM5NzQ3NjcsImp0aSI6IjMyNDMyOGJhNTA3ZDQ0MTA5NzZhMGZmNmI2ZDFjY2IxIiwidXNlcl9pZCI6MX0.1eAwajCTXHNdy0gE8LmKLSn6qDi7kZbrR1aPlbiJ08c
Accept: application/json; version=v2
Content-Type: application/json
